const $=id=>document.getElementById(id), esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let state=null, selected=null, exp=null, busy=false;
let desk=localStorage.getItem('irop-desk')||'default';$('desk').value=desk;
const num=n=>Number(n).toLocaleString('en-US'), time=n=>`${String(Math.floor(n/60)).padStart(2,'0')}:${String(n%60).padStart(2,'0')}`;
// Keep half-dollar scores exact ($136,060.50); whole dollars stay compact ($30,392).
function money(n){const x=Number(n);if(!Number.isFinite(x))return '$—';const cents=Math.round(x*100),opts=cents%100===0?{maximumFractionDigits:0}:{minimumFractionDigits:2,maximumFractionDigits:2};return '$'+(cents/100).toLocaleString('en-US',opts)}
function detailMessage(detail){if(typeof detail==='string')return detail;if(Array.isArray(detail))return detail.map(d=>d?.msg||JSON.stringify(d)).join('; ');if(detail==null)return 'Request rejected';return JSON.stringify(detail)}
async function api(path,body){const r=await fetch('/api/'+path,{method:body===undefined?'GET':'POST',headers:{'Content-Type':'application/json','X-IROP-Desk':desk},body:body===undefined?undefined:JSON.stringify(body)});const text=await r.text();let v;try{v=text?JSON.parse(text):{}}catch{v={detail:text||'Request rejected'}}if(!r.ok)throw Error(detailMessage(v.detail||text||'Request rejected'));return v}
function message(text,error=false){$('message').textContent=text;$('message').className=error?'error':''}
async function action(fn){if(busy)return;busy=true;document.body.dataset.busy='1';document.querySelectorAll('button').forEach(b=>b.disabled=true);try{await fn()}catch(e){message(e.message,true)}finally{busy=false;delete document.body.dataset.busy;document.querySelectorAll('button').forEach(b=>b.disabled=false);if(state)render();else $('scenario').hidden=true;window.refreshLiveControls?.()}}
function accept(r){state=r;exp=r.experiments.at(-1);selected=exp?.options.find(o=>o.plan===selected?.plan)||exp?.options.find(o=>o.feasible)||null;render()}
function currentView(){return $('view').value==='preview'?selected:state[$('view').value]}
function render(){if(!state)return;$('empty').hidden=true;$('scenario').hidden=false;$('scenarioName').textContent=state.name+(state.live_weather?' · observed weather + synthetic operations':'');$('phase').textContent=state.phase.toUpperCase();$('revision').textContent='Revision '+state.revision+' · '+state.id.slice(0,8);const m=state.current.metrics,d=state.disrupted?.metrics;
$('metrics').innerHTML=[['Delayed flights',m.delayed_flights,'of 60 scheduled flights',d?`${d.delayed_flights} in disrupted state`:'Baseline on time'],['Passenger delay',num(m.passenger_minutes),'passenger minutes',d?`${num(d.passenger_minutes)} in disrupted state`:'Segment-weighted minutes'],['Missed connections',m.missed_pax,'connecting passengers',d?`${d.missed_pax} in disrupted state`:'35 minute minimum transfer'],['Modeled recovery cost',money(m.cost),'illustrative cost score','Not a quoted airline cost']].map(x=>`<div class="metric"><span class="label">${x[0]}</span><strong>${x[1]}</strong><small>${x[2]}<br><em>${x[3]}</em></small></div>`).join('');
const aps=state.scenario.airports,hub=aps.PIT;$('network').innerHTML=Object.entries(aps).filter(([a])=>a!=='PIT').map(([a,p])=>`<path d="M ${hub.x} ${hub.y} Q ${(hub.x+p.x)/2} ${Math.min(hub.y,p.y)-35} ${p.x} ${p.y}" stroke="#a4bfb2" stroke-width="1.5" fill="none" stroke-dasharray="4 4"/>`).join('')+Object.entries(aps).map(([a,p])=>`<circle cx="${p.x}" cy="${p.y}" r="${a==='PIT'?23:14}" fill="${a==='PIT'?'#d5e8dc':'#f0f4f0'}"/><circle cx="${p.x}" cy="${p.y}" r="${a==='PIT'?9:5}" fill="${state.phase!=='baseline'&&state.scenario.disruptions.some(d=>d.kind==='weather'&&d.airport===a)?'#ce743d':'#277461'}"/><text x="${p.x}" y="${p.y+36}" text-anchor="middle" font-weight="700">${esc(a)}</text>${a==='PIT'?`<text x="${p.x}" y="${p.y+52}" text-anchor="middle" style="font-size:9px">PITTSBURGH HUB</text>`:''}`).join('');
$('disruptions').innerHTML=state.scenario.disruptions.map(d=>`<div class="disruption"><b>${esc(d.id)}</b><div>${esc(d.label)}<small>${esc(d.kind.toUpperCase())} · ${state.phase==='baseline'?'Ready to inject':'Included in simulation'}</small></div></div>`).join('');
$('disrupt').disabled=busy||state.phase!=='baseline';$('disrupt').textContent=state.phase==='baseline'?'Inject disruptions →':state.phase==='recovered'?'Approved — generate a new scenario':'Disruptions injected ✓';$('evaluate').disabled=busy||state.phase!=='disrupted';$('evaluate').textContent=state.phase==='recovered'?'Approved — start a new scenario to replan':state.phase==='baseline'?'Inject disruptions before comparing plans':'Compare six recovery plans →';$('cascade').textContent=d?`Without recovery: ${d.delayed_flights} delayed flights, ${d.missed_pax} missed connecting passengers, ${state.disrupted.evidence.filter(e=>!e.passed).length} failed hard checks.`:'';
renderOptions();renderTimeline();renderEvents();window.refreshLiveControls?.();}
function renderOptions(){if(!exp){$('optionList').innerHTML='<p class="placeholder">'+(state.phase==='baseline'?'Inject disruptions to unlock recovery experiments.':state.phase==='recovered'?'This scenario is already approved. Generate a new schedule to compare plans again.':'Ready to compare six fixed recovery plans. Each runs through the simulator and independent verifier.')+'</p>';$('selection').innerHTML='';$('workflow').innerHTML='';return}
$('optionList').innerHTML=exp.options.map(o=>`<article class="option ${o.feasible?'':'failed'} ${selected?.plan===o.plan?'selected':''}"><span class="rank">${o.rank?'#'+o.rank+' · FEASIBLE':o.feasible?'EVALUATED · WORKFLOW INCOMPLETE':'REJECTED · CONSTRAINT FAILURE'}</span><h3>${esc(o.title)}</h3><p>${esc(o.description)}</p><span class="cost">${money(o.metrics.cost)}<small>modeled</small></span><div class="stats">${o.metrics.delayed_flights} flights delayed · ${o.metrics.missed_pax} missed passengers<br>${num(o.metrics.passenger_minutes)} passenger delay minutes<br>${o.evidence.filter(e=>!e.passed).length} failed / ${o.evidence.length} hard checks</div><button class="quiet" data-plan="${o.plan}">${selected?.plan===o.plan?'Viewing evidence':'Inspect '+(o.feasible?'plan':'rejection')} →</button></article>`).join('');
if(selected){const failures=selected.evidence.filter(e=>!e.passed);$('selection').innerHTML=`<div class="selection"><div class="section-head"><div><h3>${esc(selected.title)} <span class="pill">${selected.feasible?'VERIFIED':'BLOCKED'}</span></h3><p>${selected.feasible?'Every modeled hard check passed. Review the preview before applying.':'This candidate cannot be approved. The verifier found the failures below.'}</p></div><button id="approve" ${!selected.feasible||state.phase!=='disrupted'||exp.status!=='completed'||exp.revision!==state.revision||busy?'disabled':''}>${state.phase==='recovered'?'Simulation already approved ✓':'Approve in simulation →'}</button></div><details ${failures.length?'open':''}><summary>Constraint evidence · ${selected.evidence.length-failures.length} passed / ${failures.length} failed</summary><label><input id="allChecks" type="checkbox"> Show passing checks too</label><div class="checks" id="checks"></div></details><details><summary>Cost breakdown</summary>${Object.entries(selected.metrics.cost_breakdown).map(([k,v])=>`<p>${esc(k.replaceAll('_',' '))}: ${money(v)}</p>`).join('')}</details></div>`;renderChecks();$('allChecks').onchange=renderChecks;const a=$('approve');if(a)a.onclick=()=>action(async()=>{const r=await api(`scenarios/${state.id}/approve`,{revision:state.revision,experiment_id:exp.id,plan:selected.plan,confirm:true});accept(r);$('view').value='current';message('Approved. The recovered schedule is saved in this simulation only.');await loadHistory()})}
$('optionList').querySelectorAll('[data-plan]').forEach(b=>b.onclick=()=>{selected=exp.options.find(o=>o.plan===b.dataset.plan);$('view').value='preview';renderOptions();renderTimeline()});
$('workflow').innerHTML=`<details><summary>${exp.mode==='local'?'Local fixed plan · no LLM':'OpenAI planner · advisory'} / ${exp.status}${exp.revision!==state.revision?' · historical experiment (earlier revision)':''} · ${exp.trace.length} trace events</summary><p>${esc(exp.error||exp.explanation)}</p>${exp.citations?.length?'<p>Verified observed citations: '+exp.citations.map(esc).join(', ')+'</p>':''}${exp.trace.map(t=>`<div class="trace"><b>${esc(t.role)}</b> / ${esc(t.action)}<details><summary>Tool / decision record</summary><pre>${esc(JSON.stringify(t.data,null,2))}</pre></details></div>`).join('')}</details>`;
}
function renderChecks(){const es=selected.evidence.filter(e=>$('allChecks')?.checked||!e.passed);$('checks').innerHTML=es.length?`<table><thead><tr><th>Evidence ID</th><th>Constraint</th><th>Subject</th><th>Result</th><th>Observed evidence</th></tr></thead><tbody>${es.map(e=>`<tr><td><code>${esc(e.id)}</code></td><td>${esc(e.kind)}</td><td>${esc(e.subject)}</td><td class="${e.passed?'pass':'fail'}">${e.passed?'PASS':'FAIL'}</td><td>${esc(e.detail)}</td></tr>`).join('')}</tbody></table>`:'<p>All modeled constraints passed. Enable passing checks to inspect the evidence.</p>'}
function renderTimeline(){const v=currentView();if(!v){$('flightTable').innerHTML='<p class="placeholder">This state is not available yet.</p>';$('connectionTable').innerHTML='';return}const rotation=$('rotation').value,fs=v.flights.filter(f=>rotation==='all'||f.rotation===Number(rotation));const lo=330,hi=Math.max(1110,...v.flights.map(f=>f.actual_arr))+30,width=n=>100*n/(hi-lo),left=n=>width(n-lo);
$('flightTable').innerHTML=`<div class="table-wrap"><table><thead><tr><th>Flight / route</th><th>Aircraft · crew</th><th>Departure</th><th>Delay</th><th><div class="time-axis"><span>05:30</span><span>${time(Math.round((lo+hi)/2))}</span><span>${time(hi)}</span></div></th><th>Why it moved</th></tr></thead><tbody>${fs.map(f=>`<tr><td><b>${esc(f.id)}</b><br>${esc(f.origin)} → ${esc(f.destination)}</td><td>${esc(f.tail)} · ${esc(f.crew)}</td><td>${time(f.actual_dep)}</td><td class="${f.delay?'fail':'pass'}">${f.delay?'+'+f.delay+'m':'On time'}</td><td><div class="flight-line" title="${esc(`Baseline ${time(f.dep)}–${time(f.arr)}; viewed ${time(f.actual_dep)}–${time(f.actual_arr)}`)}"><span class="bar" style="left:${left(f.dep)}%;width:${width(f.arr-f.dep)}%"></span><span class="bar actual ${f.delay?'delayed':''}" style="left:${left(f.actual_dep)}%;width:${width(f.actual_arr-f.actual_dep)}%"></span></div></td><td class="cause">${esc(f.causes.join(' · ')||'As scheduled')}</td></tr>`).join('')}</tbody></table></div>`;
$('connectionTable').innerHTML=`<div class="table-wrap"><table><thead><tr><th>Group</th><th>Inbound → outbound</th><th>Passengers</th><th>Transfer time</th><th>Outcome in viewed state</th></tr></thead><tbody>${v.connections.map(c=>`<tr><td>${esc(c.id)}</td><td>${esc(c.inbound)} → ${esc(c.outbound)}</td><td>${esc(c.pax)}</td><td>${esc(c.gap)}m / 35m required</td><td class="${c.missed?'fail':'pass'}">${c.missed?'Missed connection':'Connection protected'}</td></tr>`).join('')}</tbody></table></div>`}
function renderEvents(){$('events').innerHTML=state?'<details><summary>Current scenario audit · '+state.events.length+' events · '+state.experiments.length+' experiments</summary>'+state.events.map(e=>`<details><summary>${esc(e.action)} · ${esc(new Date(e.created).toLocaleTimeString())}</summary><pre>${esc(JSON.stringify(e.data,null,2))}</pre></details>`).join('')+state.experiments.map(e=>`<details><summary>Experiment ${esc(e.id.slice(0,8))} · ${esc(e.mode)} · ${esc(e.status)} · revision ${e.revision}</summary><pre>${esc(JSON.stringify({recommendation:e.recommendation,error:e.error,options:e.options.map(o=>({plan:o.plan,feasible:o.feasible,cost:o.metrics.cost})),trace:e.trace},null,2))}</pre></details>`).join('')+'</details>':''}
async function loadHistory(){const history=await api('scenarios');$('historyList').innerHTML=history.length?history.map(h=>`<div class="history-row"><div>${esc(h.name)} <small>${esc(h.phase)} · rev ${h.revision} · ${esc(new Date(h.created).toLocaleString())}</small></div><button class="quiet" data-load="${h.id}">Open →</button></div>`).join(''):'<p class="muted">Scenarios and decisions will be saved here, separately for each desk.</p>';$('historyList').querySelectorAll('[data-load]').forEach(b=>b.onclick=()=>action(async()=>{selected=null;$('view').value='current';accept(await api('scenarios/'+b.dataset.load));message('Saved scenario loaded.')}))}
function readSeed(){const raw=$('seed').value.trim(),seed=Number(raw);if(!/^\d+$/.test(raw)||!Number.isInteger(seed)||seed<0||seed>999999)throw Error('Seed must be an integer from 0 to 999999.');return seed}
$('generate').onclick=()=>action(async()=>{message('Generating and validating the baseline…');selected=null;$('view').value='current';accept(await api('scenarios',{seed:readSeed()}));message('60 flights generated. All baseline constraints pass.');await loadHistory()});
$('disrupt').onclick=()=>action(async()=>{accept(await api(`scenarios/${state.id}/disrupt`,{revision:state.revision}));message('Disruptions injected. Downstream aircraft, crew, gate, and connection effects simulated.');await loadHistory()});
$('evaluate').onclick=()=>action(async()=>{message($('live').checked?'OpenAI is requesting bounded simulations. This may take a few minutes…':'Simulating all six options and checking every constraint…');accept(await api(`scenarios/${state.id}/experiments`,{revision:state.revision,mode:$('live').checked?'live':'local',consent:$('consent').checked}));message(exp?.status==='failed'?'Workflow failed: '+exp.error:'Options evaluated. Select a plan to inspect its evidence and schedule preview.',exp?.status==='failed');await loadHistory()});
$('live').onchange=()=>{$('consentLabel').hidden=!$('live').checked;$('aiStatus').textContent=$('live').checked?'Live OpenAI · aggregate data only':'Local fixed plan · no LLM'};
$('view').onchange=renderTimeline;$('rotation').onchange=renderTimeline;for(let i=1;i<=10;i++)$('rotation').insertAdjacentHTML('beforeend',`<option value="${i}">Rotation ${i}</option>`);
document.querySelectorAll('aside nav a').forEach(a=>a.addEventListener('click',()=>{document.querySelectorAll('aside nav a').forEach(x=>x.classList.toggle('active',x===a))}));
$('refresh').onclick=()=>action(loadHistory);$('switchDesk').onclick=()=>action(async()=>{const next=$('desk').value.trim().toLowerCase();if(!/^[a-z0-9][a-z0-9_-]{0,63}$/.test(next))throw Error('Use 1–64 lowercase letters, digits, underscores, or hyphens.');desk=next;localStorage.setItem('irop-desk',desk);$('desk').value=desk;state=null;selected=null;exp=null;$('scenario').hidden=true;$('empty').hidden=false;$('events').innerHTML='';await loadHistory();await window.reloadObservations?.();message('Switched to desk '+desk)});
(async()=>{try{const status=await api('status');if(!status.live_available){$('live').disabled=true;$('aiStatus').textContent='Local fixed plan · no LLM · live mode requires server credentials'}await loadHistory()}catch(e){message(e.message,true)}})();
