let weatherSnapshot=null, aircraftSnapshot=null, liveConfig=null;
function freshWeather(s){return s?.source==='weather'&&s.environment==='production'&&s.rows.length===6&&s.rows.every(r=>{const age=Date.now()/1000-r.observed_epoch;return age>=-300&&age<=5400})}
window.refreshLiveControls=()=>{if($('weatherFreshness'))$('weatherFreshness').textContent=freshWeather(weatherSnapshot)?'current enough to project':'missing or stale data; projection blocked';$('applyWeather').disabled=busy||!state||!modern()||!freshWeather(weatherSnapshot);$('fetchAircraft').disabled=busy||!liveConfig?.fr24_configured;};
function showWeather(s){weatherSnapshot=s;const isFresh=freshWeather(s);$('weatherLive').innerHTML=`<p><b>${esc(s.provider)} · ${esc(s.environment)} observation snapshot</b> · fetched ${esc(new Date(s.fetched_at).toLocaleString())}${s.cached?' · cached':''} · <span id="weatherFreshness">${isFresh?'current enough to project':'missing or stale data; projection blocked'}</span></p><div class="table-wrap"><table><thead><tr><th>Airport</th><th>Observed (UTC)</th><th>Flight category</th><th>Wind / gust kt</th><th>Visibility SM</th></tr></thead><tbody>${s.rows.map(r=>`<tr><td>${esc(r.airport)}</td><td>${esc(r.observed_at)}</td><td>${esc(r.category)}</td><td>${esc(r.wind_kt??'?')} / ${esc(r.gust_kt??'—')}</td><td>${esc(r.visibility_sm??'?')}</td></tr>`).join('')}</tbody></table></div><details><summary>Original METAR reports / provenance</summary>${s.rows.map(r=>`<p><code>${esc(r.raw)}</code></p>`).join('')}<p>Snapshot ${esc(s.id)} · NOAA Aviation Weather Center</p></details>`;window.refreshLiveControls()}
function showAircraft(s){aircraftSnapshot=s;$('aircraftLive').innerHTML=`<p><b>${esc(s.provider)} · ${esc(s.environment)}</b> · snapshot fetched ${esc(s.fetched_at)} · ${s.rows.length} tracked objects${s.potentially_truncated?' · 50-object cap reached; incomplete':''}. Not a complete ground inventory.</p><div class="table-wrap"><table><thead><tr><th>Flight / registration</th><th>Type</th><th>Altitude ft</th><th>Speed kt</th><th>Observed</th><th>Ground status</th></tr></thead><tbody>${s.rows.map(r=>`<tr><td>${esc(r.flight)} / ${esc(r.registration)}</td><td>${esc(r.aircraft_type)}</td><td>${esc(r.altitude_ft)}</td><td>${esc(r.groundspeed_kt)}</td><td>${esc(r.observed_at||'Unknown')} ${Date.now()/1000-r.observed_epoch>300?'STALE':''}</td><td>${esc(r.ground_status)}</td></tr>`).join('')}</tbody></table></div>`}
$('fetchWeather').onclick=()=>action(async()=>{$('liveMessage').textContent='Requesting six airport observations from NOAA…';showWeather(await api('observations',{source:'weather'}));$('liveMessage').textContent='Weather snapshot saved. Review its timestamps and projection policy before applying.'});
$('fetchAircraft').onclick=()=>action(async()=>{$('liveMessage').textContent='Requesting a bounded Flightradar24 snapshot…';showAircraft(await api('observations',{source:'fr24',airport:$('liveAirport').value,consent:$('fr24Consent').checked}));$('liveMessage').textContent='Aircraft observations saved; no aircraft assignment was changed.'});
$('applyWeather').onclick=()=>action(async()=>{const r=await api(`scenarios/${state.id}/weather-projection`,{revision:state.revision,snapshot_id:weatherSnapshot.id});selected=null;$('view').value='current';accept(r);$('liveMessage').textContent='Observation-based scenario revision saved. Earlier experiments are historical; compare plans again before approval.';message('Observed weather projected using the demo policy. No official closure is implied.');await loadHistory()});
window.reloadObservations=async()=>{weatherSnapshot=null;aircraftSnapshot=null;$('weatherLive').textContent='Public NOAA airport observations · no API key required · manual refresh only.';$('aircraftLive').innerHTML='';try{liveConfig=await api('observations/status');$('fr24Status').textContent=liveConfig.fr24_configured?`Server token configured · ${liveConfig.fr24_environment} · FR24 API credits may apply.`:'FR24 is not connected. Configure FR24_API_TOKEN on the server with a separate FR24 API subscription; never paste the token into this page or chat.';const list=await api('observations');const w=list.find(s=>s.source==='weather'),a=list.find(s=>s.source==='fr24');if(w)showWeather(w);if(a)showAircraft(a);window.refreshLiveControls()}catch(e){$('liveMessage').textContent=e.message}};window.reloadObservations();
// Freshness indicators use wall-clock age, not just age at fetch. No network polling.
setInterval(()=>{window.refreshLiveControls()},30000);
